data:
  raw_data_path: "data/raw/creditcard.csv"
  processed_data_path: "data/processed/processed_data.parquet"
  train_data_path: "data/processed/train_data.parquet"
  val_data_path: "data/processed/val_data.parquet"
  test_data_path: "data/processed/test_data.parquet"

preprocessing:
  random_state: 42
  test_size: 0.15
  val_size: 0.15
  scaling_method: "standard"  # options: standard, minmax, robust
  missing_values_strategy: "median"  # options: mean, median, mode, knn

feature_engineering:
  time_window_hours: [1, 3, 6, 24]
  transaction_history_window: 10
  zscore_window: 100
  risk_score_window: 1000

model:
  random_forest:
    n_estimators: 200
    max_depth: 20
    min_samples_split: 5
    min_samples_leaf: 2
    class_weight: "balanced"
    n_jobs: -1
    random_state: 42

  xgboost:
    n_estimators: 200
    learning_rate: 0.1
    max_depth: 6
    subsample: 0.8
    scale_pos_weight: 10
    random_state: 42

training:
  cv_folds: 5
  n_trials: 100  # pour l'optimisation Optuna
  metric: "average_precision"
  early_stopping_rounds: 10
  resampling_strategy: "smote"  # options: smote, random, tomek, none

api:
  host: "0.0.0.0"
  port: 8000
  model_path: "models/trained/best_model.joblib"
  preprocessor_path: "models/trained/preprocessor.joblib"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/fraud_detection.log"
